-- Gerado por scripts/generate-seed.ts — não edite à mão.

INSERT OR REPLACE INTO settings (key, value) VALUES ('site', '{"name":"Design Mall","tagline":"Um presente para todos","seo":{"title":"Design Mall — Um presente para todos","description":"Moda, gastronomia, serviços e encontros conectados em um só lugar. Conheça as lojas, a agenda e tudo o que o Design Mall preparou para você.","image":"/images/mall-fachada-1280.webp"},"address":{"street":"Av. Lorem Ipsum, 1000","district":"Bairro Dolor","city":"Cidade","state":"UF","zip":"00000-000"},"contact":{"phone":"(00) 0000-0000","whatsapp":"","email":"contato@designmall.com.br"},"hours":[{"label":"Lojas","value":"Seg a sáb · 10h às 22h"},{"label":"Domingos e feriados","value":"14h às 20h"},{"label":"Gastronomia","value":"Todos os dias · 11h às 23h"}],"social":[{"network":"instagram","url":"https://instagram.com/"},{"network":"facebook","url":"https://facebook.com/"},{"network":"tiktok","url":"https://tiktok.com/"}],"nav":[{"label":"O Mall","href":"#conceito"},{"label":"Experiências","href":"#experiencias"},{"label":"Lojas","href":"#lojas"},{"label":"Agenda","href":"#agenda"},{"label":"Visite","href":"#visite"}],"headerCta":{"label":"Receber novidades","href":"#newsletter"},"footer":{"tagline":"Um presente para todos.","copyright":"© {ano} Design Mall. Todos os direitos reservados.","credits":"Design Life Center","columns":[{"title":"Explore","links":[{"label":"O conceito","href":"#conceito"},{"label":"Lojas","href":"#lojas"},{"label":"Agenda","href":"#agenda"},{"label":"Como chegar","href":"#visite"}]},{"title":"Atendimento","links":[{"label":"Perguntas frequentes","href":"#duvidas"},{"label":"Seja um lojista","href":"#lojista"},{"label":"Fale conosco","href":"mailto:contato@designmall.com.br"},{"label":"Newsletter","href":"#newsletter"}]}]}}');

INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('hero', 'hero', 'inicio', 10, 1, '{"eyebrow":"Design Life Center","title":"Viva\no *novo.*","subtitle":"Moda, sabores, serviços e encontros conectados em um só lugar. O Design Mall foi pensado como um presente — para a cidade e para você.","primaryCta":{"label":"Explorar lojas","href":"#lojas"},"secondaryCta":{"label":"Como chegar","href":"#visite"},"image":{"src":"/images/mall-fachada-2400.webp","srcset":"/images/mall-fachada-1280.webp 1280w, /images/mall-fachada-2400.webp 2400w","alt":"Fachada do Design Mall com torre e galerias de lojas","width":2400,"height":1698},"imageTone":"brand","highlights":[{"value":"+120","label":"lojas e serviços"},{"value":"7 dias","label":"por semana"},{"value":"1.200","label":"vagas cobertas"}],"scrollLabel":"Role para descobrir"}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('marquee-categorias', 'marquee', NULL, 20, 1, '{"items":["Moda","Gastronomia","Serviços","Bem-estar","Kids","Casa & Design","Cultura","Encontros"],"duration":38}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('manifesto', 'manifesto', 'conceito', 30, 1, '{"eyebrow":"O conceito","text":"Todo presente começa com cuidado. Por isso cada detalhe do Design Mall foi pensado para que a sua visita seja como **abrir algo especial**: um ambiente bonito, feito para pessoas e sempre preocupado em **oferecer o melhor** para quem chega. Aqui, o novo é para **todos**.","signature":"Um presente para todos.","image":{"src":"/images/presente-sacola-1600.webp","srcset":"/images/presente-sacola-800.webp 800w, /images/presente-sacola-1600.webp 1600w","alt":"Sacola do Design Mall com grafismos coloridos"},"caption":"A sacola que vira presente: o símbolo que inspirou a nossa marca."}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('experiencias', 'experiences', 'experiencias', 40, 1, '{"eyebrow":"Experiências","title":"Tudo o que você procura, *conectado.*","subtitle":"Do look da semana ao café com quem você gosta: um mix pensado para o seu dia a dia — e para os dias especiais também.","items":[{"title":"Moda & Acessórios","description":"Marcas que vestem do básico ao inesquecível.","icon":"bag","tone":"pink","category":"moda"},{"title":"Gastronomia","description":"Cafés, restaurantes e sabores para todas as horas.","icon":"utensils","tone":"teal","category":"gastronomia"},{"title":"Serviços","description":"Praticidade para resolver a vida em um só endereço.","icon":"scissors","tone":"violet","category":"servicos"},{"title":"Bem-estar","description":"Saúde, beleza e cuidado para corpo e mente.","icon":"heart","tone":"teal","category":"bem-estar"},{"title":"Kids & Lazer","description":"Diversão para os pequenos e programas em família.","icon":"smile","tone":"pink","category":"kids"},{"title":"Casa & Design","description":"Peças e ideias para deixar seu espaço com a sua cara.","icon":"home","tone":"violet","category":"casa"}]}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('lojas', 'stores', 'lojas', 50, 1, '{"eyebrow":"Lojas","title":"Marcas que fazem parte *da nossa história.*","subtitle":"Filtre por experiência e descubra onde encontrar cada uma delas.","showFilters":true,"featuredOnly":false,"limit":12,"allLabel":"Todas","cta":{"label":"Ver todas as lojas","href":"/lojas"}}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('agenda', 'events', 'agenda', 60, 1, '{"eyebrow":"Acontece aqui","title":"Sempre tem algo *novo* para viver.","subtitle":"Eventos, campanhas e experiências que transformam cada visita em um encontro.","hideExpired":true}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('conexao', 'stats', 'conexao', 70, 1, '{"eyebrow":"Conexão com tudo e todos","title":"Formas que se encontram. *Pessoas também.*","subtitle":"","text":"Nossos grafismos nasceram das conexões orgânicas entre etnias, culturas e estilos — diversidade transformada em arte. É essa mistura que dá vida ao Design Mall.","items":[{"value":120,"prefix":"+","suffix":"","label":"lojas e serviços"},{"value":35,"prefix":"","suffix":" mil m²","label":"para viver e conviver"},{"value":1200,"prefix":"","suffix":"","label":"vagas de estacionamento"},{"value":365,"prefix":"","suffix":"","label":"dias de programação"}]}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('lojista', 'feature', 'lojista', 80, 1, '{"eyebrow":"Seja um lojista","title":"Sua marca no lugar *mais conectado* da cidade.","subtitle":"","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Espaços versáteis, fluxo qualificado e um time dedicado a fazer a sua operação crescer junto com a gente.","image":{"src":"/images/grafismos-parede-1600.webp","srcset":"/images/grafismos-parede-800.webp 800w, /images/grafismos-parede-1600.webp 1600w","alt":"Parede com os grafismos geométricos do Design Mall"},"cta":{"label":"Falar com o comercial","href":"mailto:comercial@designmall.com.br"},"reverse":false,"bullets":["Lojas de 30 a 600 m²","Quiosques e espaços de experiência","Mídia e ativações de marca"]}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('visite', 'visit', 'visite', 90, 1, '{"eyebrow":"Visite","title":"Fácil de chegar. *Difícil de ir embora.*","subtitle":"No coração da cidade, com estacionamento coberto, acessibilidade e tudo pensado para o seu conforto.","mapEmbedUrl":"","mapsUrl":"https://maps.google.com/?q=Design+Mall","wazeUrl":"https://waze.com/ul?q=Design%20Mall","image":{"src":"/images/estacionamento-1400.webp","srcset":"/images/estacionamento-720.webp 720w, /images/estacionamento-1400.webp 1400w","alt":"Estacionamento coberto do Design Mall"},"info":[{"icon":"car","title":"Estacionamento","text":"1.200 vagas cobertas, preferenciais e bicicletário."},{"icon":"navigation","title":"Transporte público","text":"Ponto de ônibus em frente à entrada principal."},{"icon":"wifi","title":"Wi-Fi gratuito","text":"Conexão rápida em todos os pisos."},{"icon":"gift","title":"Embrulho para presente","text":"Grátis no balcão de atendimento. É a nossa cara."}]}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('duvidas', 'faq', 'duvidas', 100, 1, '{"eyebrow":"Dúvidas","title":"Perguntas *frequentes.*","subtitle":"Não encontrou o que procurava? Fale com a gente pelo e-mail contato@designmall.com.br.","items":[{"question":"Qual é o horário de funcionamento?","answer":"As lojas abrem de segunda a sábado, das 10h às 22h, e aos domingos e feriados, das 14h às 20h. A gastronomia funciona todos os dias, das 11h às 23h."},{"question":"O estacionamento é pago?","answer":"Os primeiros 15 minutos são gratuitos. Lorem ipsum dolor sit amet: consulte a tabela completa nos totens de pagamento e no balcão de atendimento."},{"question":"Posso levar meu pet?","answer":"Sim! O Design Mall é pet friendly. Pets de pequeno porte são bem-vindos nas áreas comuns, com guia ou no colo."},{"question":"Vocês fazem embrulho para presente?","answer":"Claro — presente é a nossa essência. O embrulho é gratuito no balcão de atendimento, no piso térreo."},{"question":"Como abro uma loja no Design Mall?","answer":"Fale com o nosso time comercial pelo e-mail comercial@designmall.com.br. Vamos adorar conhecer a sua marca."},{"question":"Como fico sabendo de eventos e promoções?","answer":"Assine a nossa newsletter aqui embaixo e siga o Design Mall nas redes sociais. As novidades chegam primeiro por lá."}]}');
INSERT OR REPLACE INTO sections (id, type, anchor, position, enabled, data) VALUES ('newsletter', 'newsletter', 'newsletter', 110, 1, '{"eyebrow":"Newsletter","title":"Abra um presente *toda semana.*","text":"Novidades das lojas, agenda de eventos e convites exclusivos direto no seu e-mail. Leve, curtinha e sem spam.","substackUrl":"","mode":"form","placeholder":"seu@email.com","buttonLabel":"Quero receber","disclaimer":"Enviada pelo Substack. Você pode cancelar a inscrição quando quiser.","successMessage":"Pronto! Confira seu e-mail para confirmar a inscrição.","pendingMessage":"Nossa newsletter está quase pronta. Volte em breve!","perks":["Convites para eventos","Ofertas das lojas","Lançamentos em primeira mão"]}');

INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-moda', 'moda', 'Moda & Acessórios', 'pink', 'bag', 10);
INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-gastronomia', 'gastronomia', 'Gastronomia', 'teal', 'utensils', 20);
INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-servicos', 'servicos', 'Serviços', 'violet', 'scissors', 30);
INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-bem-estar', 'bem-estar', 'Bem-estar', 'teal', 'heart', 40);
INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-kids', 'kids', 'Kids & Lazer', 'pink', 'smile', 50);
INSERT OR REPLACE INTO categories (id, slug, name, tone, icon, position) VALUES ('cat-casa', 'casa', 'Casa & Design', 'violet', 'home', 60);

INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-lorem-moda', 'lorem-moda', 'Lorem Moda', 'cat-moda', 'Piso 1', 'Loja 104', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco.', NULL, NULL, '', '', '', '', '', '[]', 1, 10, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-ipsum-cafe', 'ipsum-cafe', 'Ipsum Café', 'cat-gastronomia', 'Térreo', 'Loja 012', 'Sed do eiusmod tempor incididunt ut labore et dolore magna.', 'Sed do eiusmod tempor incididunt ut labore et dolore magna. Duis aute irure dolor in reprehenderit in voluptate velit.', NULL, NULL, '', '', '', '', '', '[]', 1, 20, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-dolor-studio', 'dolor-studio', 'Dolor Studio', 'cat-servicos', 'Piso 2', 'Loja 215', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco.', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco. Excepteur sint occaecat cupidatat non proident, sunt in culpa.', NULL, NULL, '', '', '', '', '', '[]', 0, 30, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-amet-beauty', 'amet-beauty', 'Amet Beauty', 'cat-bem-estar', 'Piso 1', 'Loja 131', 'Duis aute irure dolor in reprehenderit in voluptate velit.', 'Duis aute irure dolor in reprehenderit in voluptate velit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.', NULL, NULL, '', '', '', '', '', '[]', 1, 40, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-sit-kids', 'sit-kids', 'Sit Kids', 'cat-kids', 'Piso 2', 'Loja 240', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa.', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', NULL, NULL, '', '', '', '', '', '[]', 0, 50, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-consectetur-casa', 'consectetur-casa', 'Consectetur Casa', 'cat-casa', 'Piso 2', 'Loja 202', 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur.', 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur. Sed do eiusmod tempor incididunt ut labore et dolore magna.', NULL, NULL, '', '', '', '', '', '[]', 1, 60, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-adipiscing-jeans', 'adipiscing-jeans', 'Adipiscing Jeans', 'cat-moda', 'Piso 1', 'Loja 118', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco.', NULL, NULL, '', '', '', '', '', '[]', 0, 70, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-elit-bistro', 'elit-bistro', 'Elit Bistrô', 'cat-gastronomia', 'Térreo', 'Loja 021', 'Sed do eiusmod tempor incididunt ut labore et dolore magna.', 'Sed do eiusmod tempor incididunt ut labore et dolore magna. Duis aute irure dolor in reprehenderit in voluptate velit.', NULL, NULL, '', '', '', '', '', '[]', 0, 80, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-tempor-fit', 'tempor-fit', 'Tempor Fit', 'cat-bem-estar', 'Piso 3', 'Loja 301', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco.', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco. Excepteur sint occaecat cupidatat non proident, sunt in culpa.', NULL, NULL, '', '', '', '', '', '[]', 0, 90, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-magna-otica', 'magna-otica', 'Magna Ótica', 'cat-servicos', 'Piso 1', 'Loja 109', 'Duis aute irure dolor in reprehenderit in voluptate velit.', 'Duis aute irure dolor in reprehenderit in voluptate velit. Nemo enim ipsam voluptatem quia voluptas sit aspernatur.', NULL, NULL, '', '', '', '', '', '[]', 0, 100, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-aliqua-atelier', 'aliqua-atelier', 'Aliqua Atelier', 'cat-moda', 'Piso 1', 'Loja 122', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa.', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', NULL, NULL, '', '', '', '', '', '[]', 1, 110, 1);
INSERT OR REPLACE INTO stores (id, slug, name, category_id, floor, unit, short_description, description, logo_url, cover_url, phone, whatsapp, instagram, website, hours, tags, featured, position, active) VALUES ('store-veniam-burger', 'veniam-burger', 'Veniam Burger', 'cat-gastronomia', 'Térreo', 'Loja 030', 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur.', 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur. Sed do eiusmod tempor incididunt ut labore et dolore magna.', NULL, NULL, '', '', '', '', '', '[]', 0, 120, 1);

INSERT OR REPLACE INTO events (id, slug, title, tag, description, image_url, starts_at, ends_at, cta_label, cta_url, position, active) VALUES ('evt-semana-moda', 'semana-moda', 'Semana Moda', 'Moda', 'Desfiles, lançamentos e condições especiais nas lojas participantes. Lorem ipsum dolor sit amet.', '/images/campanha-semana-moda-1400.webp', '2026-10-19', '2026-10-25', 'Ver programação', '#agenda', 10, 1);
INSERT OR REPLACE INTO events (id, slug, title, tag, description, image_url, starts_at, ends_at, cta_label, cta_url, position, active) VALUES ('evt-viva-o-novo', 'viva-o-novo', 'Viva o novo', 'Campanha', 'A temporada que celebra o que acabou de chegar: novas marcas, novas coleções e novas experiências.', '/images/campanha-viva-o-novo-1400.webp', '2026-10-01', '2026-11-30', 'Saiba mais', '#agenda', 20, 1);
INSERT OR REPLACE INTO events (id, slug, title, tag, description, image_url, starts_at, ends_at, cta_label, cta_url, position, active) VALUES ('evt-play-kids', 'play-kids', 'Play Kids', 'Família', 'Oficinas, brincadeiras e espetáculos para a criançada todos os fins de semana. Consectetur adipiscing elit.', '/images/campanha-redes-1400.webp', '2026-10-10', '2026-10-12', 'Inscrever meu filho', '#agenda', 30, 1);
INSERT OR REPLACE INTO events (id, slug, title, tag, description, image_url, starts_at, ends_at, cta_label, cta_url, position, active) VALUES ('evt-bem-estar', 'conectado-bem-estar', 'Conectado com o seu bem-estar', 'Bem-estar', 'Aulas abertas, avaliações gratuitas e bate-papos sobre saúde e autocuidado. Sed do eiusmod tempor.', '/images/campanha-bem-estar-1400.webp', '2026-11-03', '2026-11-08', 'Ver agenda', '#agenda', 40, 1);
INSERT OR REPLACE INTO events (id, slug, title, tag, description, image_url, starts_at, ends_at, cta_label, cta_url, position, active) VALUES ('evt-noites-design', 'noites-de-design', 'Noites de Design', 'Cultura', 'Exposições, música ao vivo e encontros com artistas locais no átrio central. Ut enim ad minim veniam.', '/images/painel-interno-1400.webp', '2026-11-14', NULL, 'Quero ir', '#agenda', 50, 1);
